<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8" />

      <style>
         body {
            font-family: DejaVu Sans;
            font-size: 12px;
            color: #222;
            margin: 30px;
         }

         .header {
            width: 100%;
            border-bottom: 3px solid #162d4d;
            padding-bottom: 15px;
            margin-bottom: 30px;
         }

         .logo {
            width: 120px;
         }

         .title {
            font-size: 28px;
            font-weight: bold;
            color: #162d4d;
            margin-top: 15px;
         }

         .subtitle {
            color: #777;
            margin-top: 5px;
         }

         .summary {
            border: 1px solid #ddd;
            border-radius: 10px;
            padding: 18px;
            margin-top: 25px;
         }

         .summary h2 {
            color: #162d4d;
            margin-top: 0;
         }

         table {
            width: 100%;
            border-collapse: collapse;
         }

         td {
            padding: 8px 0;
         }

         .label {
            color: #666;
            width: 180px;
         }

         .value {
            font-weight: bold;
         }

         .highlight {
            margin-top: 25px;
            border: 1px solid #eee;
            padding: 18px;
         }

         .highlight h2 {
            color: #f3a344;
         }

         .day {
            background: #162d4d;
            color: white;
            padding: 10px;
            font-size: 18px;
            margin-top: 40px;
         }

         .card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
            margin-top: 15px;
         }

         .name {
            font-size: 18px;
            font-weight: bold;
         }

         .address {
            color: #777;
         }

         .desc {
            margin-top: 10px;
         }

         .cost {
            margin-top: 10px;
            font-weight: bold;
            color: #162d4d;
         }

         .distance {
            text-align: center;
            color: #f3a344;
            margin: 15px 0;
            font-weight: bold;
         }

         .closing{
            margin-top:50px;
            padding:25px;
            text-align:center;
        }

        .closing h3{
            color:#162d4d;
            font-size:22px;
            margin-bottom:10px;
        }

        .closing p{
            color:#666;
            line-height:1.8;
            font-size:13px;
        }

         .footer {
            position: fixed;
            bottom: -15px;
            left: 0;
            right: 0;

            text-align: center;
            font-size: 10px;
            color: #888;
         }
      </style>
   </head>

   <body>
      <div class="header">
         <img src="{{ public_path('assets/logo.png') }}" class="logo" />
         <div class="title">Personal Travel Itinerary</div>
         <div class="subtitle">Generated by WayGo</div>
      </div>

      @php $first = $trip->first(); @endphp

      <div class="summary">
            <h2>Personal Information</h2>
            <table>
                <tr>
                    <td class="label">Full Name</td>
                    <td class="value">{{ $user->name }}</td>
                </tr>
                <tr>
                    <td class="label">Email</td>
                    <td class="value">{{ $user->email }}</td>
                </tr>
                <tr>
                    <td class="label">Phone Number</td>
                    <td class="value">{{ $user->phone }}</td>
                </tr>
            </table>
        </div>

      <div class="summary">
         <h2>Trip Summary</h2>
         <table>
            <tr>
               <td class="label">Destination</td>
               <td class="value">{{ explode(',',$first->location)[0] }}</td>
            </tr>
            <tr>
               <td class="label">Travel Date</td>
               <td class="value">
                  {{ Carbon\Carbon::parse($first->start_date)->format('d M Y')
                  }} - {{ Carbon\Carbon::parse($first->end_date)->format('d M
                  Y') }}
               </td>
            </tr>

            <tr>
               <td class="label">Duration</td>
               <td class="value">
                  {{
                  Carbon\Carbon::parse($first->start_date)->diffInDays(Carbon\Carbon::parse($first->end_date))+1
                  }} Days
               </td>
            </tr>

            <tr>
               <td class="label">Travelers</td>
               <td class="value">
                  {{ $first->adults }} Adult @if($first->children>0) + {{
                  $first->children }} Kids @endif
               </td>
            </tr>

            <tr>
               <td class="label">Estimated Budget</td>
               <td class="value">
                  Rp {{ number_format($totalBudget,0,',','.') }}
               </td>
            </tr>
         </table>
      </div>

      <div class="highlight">
         <h2>Travel Highlights</h2>
         <ul>
            @foreach($trip->take(5) as $item)
                <li>{{ $item->destination_name }}</li>
            @endforeach
         </ul>
      </div>

      @php $currentDay=0; @endphp @foreach($trip as $index=>$item)
      @if($currentDay!=$item->day) @php $currentDay=$item->day; @endphp

      <div class="day">Day {{ $item->day }}</div>

      @endif

      <div class="card">
         <div class="name">
            {{ $item->destination_name }}
         </div>

         <div class="address">{{ $item->address }}</div>
         <div>&#9733; {{ $item->rating }}</div>
         <div class="desc">{{ $item->description }}</div>

         <div class="cost">
            Estimated Cost

            <br />

            Rp {{ number_format($item->estimated_cost,0,',','.') }}
         </div>
      </div>
      @endforeach

    <!-- <div class="closing">
        <h3>Enjoy Your Journey!</h3>
        <p>
            Wherever you go, go with all your heart. Thank you for trusting WayGo to plan your adventure.
        </p>
    </div> -->

      <div class="footer">
         Generated by WayGo • {{ now()->format('d M Y H:i') }}
      </div>
   </body>
</html>
